### ISSUE TITLE
npm install失败，找不到sentry，请问如何解决？

### ISSUE THREAD

**Issue by WinLXY** [mcuking/mobile-web-best-practice#15]
6835 timing command:install Completed in 57442ms
6836 verbose stack Error: command failed
6836 verbose stack     at ChildProcess.<anonymous> (C:\Users\l00288921\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:63:27)
6836 verbose stack     at ChildProcess.emit (node:events:527:28)
6836 verbose stack     at maybeClose (node:internal/child_process:1092:16)
6836 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
6837 verbose pkgid @sentry/cli@1.74.5
6838 verbose cwd D:\03-Code\01-ExcellentCode\03-vue\mobile-web-best-practice-master
6839 verbose Windows_NT 10.0.19044
6840 verbose node v16.16.0
6841 verbose npm  v8.15.0
6842 error code 1
6843 error path D:\03-Code\01-ExcellentCode\03-vue\mobile-web-best-practice-master\node_modules\@sentry\cli
6844 error command failed
6845 error command C:\WINDOWS\system32\cmd.exe /d /s /c C:\Users\L00288~1\AppData\Local\Temp\install-3fba2495.cmd
6846 error info sentry-cli Downloading from https://downloads.sentry-cdn.com/sentry-cli/1.74.5/sentry-cli-Windows-x86_64.exe
6846 error Error: Unable to download sentry-cli binary from https://downloads.sentry-cdn.com/sentry-cli/1.74.5/sentry-cli-Windows-x86_64.exe.
6846 error Error code: ETIMEDOUT
6847 verbose exit 1

**Comment by GdgmPhs** [comment]
我也是这个问题

**Comment by mcuking** [comment]
> 6835 timing command:install Completed in 57442ms 6836 verbose stack Error: command failed 6836 verbose stack at ChildProcess. (C:\Users\l00288921\AppData\Roaming\npm\node_modules\npm\node_modules@npmcli\promise-spawn\lib\index.js:63:27) 6836 verbose stack at ChildProcess.emit (node:events:527:28) 6836 verbose stack at maybeClose (node:internal/child_process:1092:16) 6836 verbose stack at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) 6837 verbose pkgid @sentry/cli@1.74.5 6838 verbose cwd D:\03-Code\01-ExcellentCode\03-vue\mobile-web-best-practice-master 6839 verbose Windows_NT 10.0.19044 6840 verbose node v16.16.0 6841 verbose npm v8.15.0 6842 error code 1 6843 error path D:\03-Code\01-ExcellentCode\03-vue\mobile-web-best-practice-master\node_modules@sentry\cli 6844 error command failed 6845 error command C:\WINDOWS\system32\cmd.exe /d /s /c C:\Users\L00288~1\AppData\Local\Temp\install-3fba2495.cmd 6846 error info sentry-cli Downloading from https://downloads.sentry-cdn.com/sentry-cli/1.74.5/sentry-cli-Windows-x86_64.exe 6846 error Error: Unable to download sentry-cli binary from https://downloads.sentry-cdn.com/sentry-cli/1.74.5/sentry-cli-Windows-x86_64.exe. 6846 error Error code: ETIMEDOUT 6847 verbose exit 1

我这里主要是用 mac 开发，倒没遇到过这个问题。
这个项目升级了一些依赖的版本，也上传了 package-lock 文件，可以再试试？
@WinLXY @GdgmPhs
